FROM rocm/dev-ubuntu-24.04:7.1-complete as builder

WORKDIR /root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        cmake \
        libomp-20-dev \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY third_party third_party
COPY cli cli
COPY include include
COPY src src
COPY cmake cmake
COPY python python
COPY CMakeLists.txt .

ARG PYTORCH_ROCM_ARCH
ENV PYTORCH_ROCM_ARCH=${PYTORCH_ROCM_ARCH:-"gfx1201"}

# RUN CLANG_CMAKE_CXX_COMPILER=amdclang++ CXX=amdclang++ HIPCXX="$(hipconfig -l)/clang" HIP_PATH="$(hipconfig -R)" \
#     cmake -S . -B build -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DWITH_MKL=OFF -DWITH_HIP=ON \
#     -DCMAKE_HIP_ARCHITECTURES=$PYTORCH_ROCM_ARCH -DWITH_DNNL=OFF -DBUILD_TESTS=ON -DWITH_CUDNN=ON

RUN mkdir build_tmp && \
    cd build_tmp && \
    CLANG_CMAKE_CXX_COMPILER=amdclang++ CXX=amdclang++ HIPCXX="$(hipconfig -l)/clang" HIP_PATH="$(hipconfig -R)" \
    cmake -DCMAKE_INSTALL_PREFIX=${CTRANSLATE2_ROOT} -DCMAKE_POLICY_VERSION_MINIMUM=3.5  -DWITH_HIP=ON \
          -DCMAKE_HIP_ARCHITECTURES=$PYTORCH_ROCM_ARCH -DWITH_MKL=OFF -DWITH_DNNL=OFF -DWITH_CUDNN=ON \
          -DCMAKE_BUILD_TYPE=Release .. && \
    VERBOSE=1 make -j$(nproc) install

ENV CTRANSLATE2_ROOT=/opt/ctranslate2
ENV LD_LIBRARY_PATH=/usr/local/lib/:${LD_LIBRARY_PATH}

# RUN cmake --build build -- -j
# RUN cd build && cmake --install . --prefix $CTRANSLATE2_ROOT
# RUN ldconfig

ENV LANG=en_US.UTF-8
COPY README.md .

RUN cd python && \
    python3 -m pip --no-cache-dir install -r install_requirements.txt && \
    python3 setup.py bdist_wheel --dist-dir $CTRANSLATE2_ROOT
# RUN pip install $CTRANSLATE2_ROOT/*.whl

FROM rocm/dev-ubuntu-24.04:7.1-complete

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libomp-20-dev \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV CTRANSLATE2_ROOT=/opt/ctranslate2
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CTRANSLATE2_ROOT/lib

COPY --from=builder $CTRANSLATE2_ROOT $CTRANSLATE2_ROOT
RUN python3 -m pip --no-cache-dir install $CTRANSLATE2_ROOT/*.whl && \
    rm $CTRANSLATE2_ROOT/*.whl

ENTRYPOINT ["/opt/ctranslate2/bin/ct2-translator"]
